apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - web-deployment.yaml
  - web-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - ingress.yaml
  - configmap.yaml

images:
- name: <YOUR_ECR_REGISTRY_URL>/my-web-app # This is the placeholder for Kustomize
  newName: <YOUR_ECR_REGISTRY_URL>/my-web-app # Will be updated by GitHub Actions build step
  newTag: latest # This tag will be dynamically replaced by the SHA from the build step