apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels:
    app: web-app
spec:
  replicas: 2 # Start with 2 replicas for High Availability
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: <YOUR_ECR_REGISTRY_URL>/my-web-app:latest # This will be replaced by Kustomize/GitOps
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis-service # Name of the Redis Kubernetes Service
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
      # Optional: Add IRSA if your web app needed AWS permissions
      # serviceAccountName: my-web-app-service-account # If your app needs AWS permissions