# Use the official Redis image from Docker Hub
FROM redis:6.2-alpine

# You can add custom configurations here if needed.
# For example, copying a redis.conf file:
# COPY redis.conf /usr/local/etc/redis/redis.conf
# CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]

# Expose the default Redis port
EXPOSE 6379

# The default command for the Redis image runs redis-server
CMD ["redis-server"]